### ISSUE TITLE
NLCH-0001  Check that issues are disctributed to members

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#1]
Задание NLCH-0001
1.	Создайте аккаунт на github.com 
2.	Создайте аккаунт на stackoverflow.com, авторизуйтесь с ним на ru.stackoverflow.com.
3.	Форкните репозиторий https://github.com/NashaLeptaChallenge/nasha_lepta
4.	Выполните issue 2, установив Chrome plugin от www.zenhub.io, детали использования — www.screenr.com/fWiH . Это позволит Вам создавать свои личные TODO, голосовать за решения...
5.	Всех участников, который скопируют репозиторий я добавлю, в команду разработки, https://github.com/orgs/NashaLeptaChallenge/teams (ссылка закрыта для остальных) , это позволит всем получать уведомления при упоминании @NashaLeptaChallenge/team, потом я создам другие команды для модерации.
Можно также получать все уведомления по репозиторию, если Вы нажмёте кнопку Watch, в правом углу на странице репозитория.

**Comment by Shketkol** [comment]
Fixes #1

**Comment by Shketkol** [comment]
Как сделать коммит с 	Fixes #1 в issue

**Comment by SergiiShapoval** [comment]
@Shketkol сделай любые незначительные изменения (добавь комментарий) и при коммите добавь Fixes #1

**Comment by alexkazantsev** [comment]
> Как сделать коммит с Fixes #1 в issue

`$ cd <path_to_project_folder>`
`$ echo "<\!-- some_your_dummy_code -->" >> public/404.html `
`$ git commit -am "Fixes #1 : <your_comment>`
`$ git push`

**Comment by SergiiShapoval** [comment]
@alexkazantsev как-то сильно сложно, используйте Webstorm, в меню VCS ищите commit и push

**Comment by SergiiShapoval** [comment]
> И кстати, не могу выполнить пункт 5 первого задания (5. Добавьтесь в github команду — github.com/...LeptaChallenge/teams/team)- Git не находит такую команду.

всех пользователей, которые форкнут проект, я добавлю в команду, ссылка к сожалению не видне другим участникам

**Comment by SergiiShapoval** [comment]
> указал адрес ****.
Но из-за пересылок почты между ящиками в вашей группе я зарегистрировался с адресом ****.
Наверное из-за этого мне не разрешено просматривать сообщения этой группы.


просмотр сообщений был запрещён, теперь разрешён, но сообщений там сейчас нету, поскольку я высылал только приглашения, жду пока подтвердятся остальные участники.

автор этого письма добавлен в рассылку под обоими адресами, но один подтверждён второй нет - гугл использует первый авторизованный email и игнорирует второй = решение выйдите и авторизуйтесь заново под аккаунтом на который хотите получать почту, на втором потом отпишитесь

**Comment by kaflan** [comment]
Оперативненько. клево интересно. Нжно сделать пулл потом плу реквест чтобы чтото закомитить насколько я помню?

**Comment by SergiiShapoval** [comment]
> Оперативненько. клево интересно. Нжно сделать пулл потом плу реквест чтобы чтото закомитить насколько я помню?

гляньте в курсе, который я высылал на почту

**Comment by ArtemMaznov** [comment]
Fixes #1

**Comment by romanfedyshyn** [comment]
Fixes #1 done )

**Comment by kaidzen** [comment]
Done: https://github.com/kaidzen/nasha_lepta/commit/f4aaf2e6bcf8db41e50e01a20b8581f6b20ed3ee

**Comment by SergiiShapoval** [comment]
@ArtemMaznov не вижу твоего коммита

**Comment by SergiiShapoval** [comment]
reopen

**Comment by kaflan** [comment]
@SergiiShapoval EAP юзать норм?

**Comment by SergiiShapoval** [comment]
@kaflan не понял вопрос
