### ISSUE TITLE
NLCH-0009 Добавляем динамические routes для статей.

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#11]
Следующие задания направленны на разработку конкретной фичи. Следовательно, в описании задачи будет меньше описания того, что и как нужно делать, a больше Acceptance criteria - того, что нужно получить, и чему должно соответствовать решение.

Описание желаемого поведения приложения:
Как редактор сайта, я хочу самостоятельно добавлять новые статьи и редактировать старые:
1.	все операции, относящиеся, к статьям должны быть сгруппированы под путём **"/articles/*"** 
2.	на **"/articles/new"** должна быть возможность добавить новую статью:
2.1.	редактор сам задаёт название url подстраницы английскими буквами, подчёркиванием и дефисом (NB: опция валидации, каким способом оптимальнее всего реализовать? https://htmlpreview.github.io/?https://github.com/angular-ui/ui-validate/master/demo/index.html)
2.2.	редактор должен иметь возможность редактировать текст, как в визуальном редакторе (NB: каким образом работает текущая интеграция с ckeditor?) с опцией предпросмотра
3.	на страницах типа **"/articles/:id"** редактор может просмотреть и отредактировать (в визуальном редакторе) страницу с опцией предпросмотра
4.	текущие статьи должны быть мигрированы на новую логику, а именно:
4.1.	article1
4.2.	article2
4.3.	article3
4.4.	остальные удалить
5.	Логика должна быть расширяемой = работать и на подстраницах типа **/nikolsky_evenings/** и других
Доп. материалы должны быть на почте, у всех кто форкнул проект.
Просьба сохранять изменения коммитами в отдельной ветке – articles, как работать с ветками детальнее тут - https://youtu.be/F14RTiO3bc0 , упоминаем в коммитах Fixes #11, чтобы другие могли использовать Ваши наработки и мы экономили друг другу время

**Comment by SergiiShapoval** [comment]
https://docs.angularjs.org/guide/providers

**Comment by kaflan** [comment]
Кто сделал? ты?
