### ISSUE TITLE
NLCH-0010 Добавляем динамические routes для новостей

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#12]
Зависит от #11 

Как редактор сайта, я хочу самостоятельно добавлять новые новости и редактировать старые:
1.	все операции, относящиеся, к новостям должны быть сгруппированы под путями "/news/*" и "/news"
2.	фича новостей должна уметь всё тоже самое, что и фича статей + указанные ниже (можно ли здесь применить наследование?)
3.	на "/news " должны быть перечислены все анонсы новостей (1 фото + неформатированный текст) в порядке убывания даты размещения;
4.	текст анонса должен быть строго ограничен количеством символов, к-во символов определяется в едином месте приложения (какой angular service recipe нужно использовать для этого?)
5.	анонс новости играет роль ссылки на описание новости в виде Rich Text Format ( = форматирование из ckeditor)
6.	дополнительные параметры логики сайта либо добавляются редактором напрямую, либо задаются по умолчанию, а именно:
6.1.	дата новости (выбор из календаря, с возможностью прописать напрямую – используем Datepicker из http://angular-ui.github.io/bootstrap/), вставляем текущую  дату по умолчанию;
6.2.	выбор картинки = ссылка на картинку с динамической подгрузкой картинки, все картинки будут хостится на picasa
6.3.	текст анонс автоматически генерируется из вставленных данных в поле редактирования ckeditor, если был однажды изменён вручную – больше не генерируется.
Коммитим изменения в ветке news, упоминаем в коммитах Fixes #12

**Comment by kaflan** [comment]
в процессе

**Comment by kaflan** [comment]
moment.js можна юзать?

**Comment by SergiiShapoval** [comment]
зачем?

**Comment by kaflan** [comment]
пунк 6.3 не понятен чутка

**Comment by SergiiShapoval** [comment]
пользователь редактирует html элементы в поле  ckeditor, данное поле превращаешь из html  в  простой текст и вырезаешь первые символы (пусть будет как в твите - 160, данное число должно настраиваться в одном месте)

если пользователь уже начал сам редактировать сокращённый текст - больше не отталкиваемся от того что написано в Ckeditor, а используем то, что написано в поле напрямую

**Comment by kaflan** [comment]
ух устроился на работу но интересно закончить)

**Comment by SergiiShapoval** [comment]
@kaflan я закрыл таску, посмотри коммиты
