### ISSUE TITLE
Общие вопроссы и благодарности =)

### ISSUE THREAD

**Issue by kaflan** [NashaLeptaChallenge/nasha_lepta#14]
Хочу сказать спасибо за даннный проэкт.. очень помогает в изучении ангуляр и мира веба) я думал сделать похожую цмс... спасибо за подсказку)  буду использовать)

**Comment by kaflan** [comment]
я после установки плагина веббрейнс не могу + нажать

**Comment by katana-ua** [comment]
Возможно, кого-то заинтересует - на Skillshare выгодное предложение: 3 месяца доступа ко всем курсам за $0.99. Конечно, это не кодскул, где сразу же можно себя проверить, но все равно полезно - тем более, почти даром ) Как раз смотрю курс по ангуляру - даже шире и подробнее, чем на CodeSchool. В общем, рекомендую. 
Ссылка: http://skl.sh/1JnIxv2

**Comment by kaflan** [comment]
https://github.com/kaflan/NG6-starter
что можете сказать об этом?

**Comment by katana-ua** [comment]
Получила opensourse-лицензию на Webstorm, т.е. кому надо - можно подавать заявку (рассматривали примерно неделю).

**Comment by SergiiShapoval** [comment]
@NashaLeptaChallenge/team обратите внимание на дополнительный бонус для активных участников - лицензия Webstorm

**Comment by kaflan** [comment]
@katana-ua  красава) у меня просто времени не так много свободного

**Comment by SergiiShapoval** [comment]
картинки привата для ускоренной загрузки - прикольно сделали - https://privat24.privatbank.ua/p24/img/main_sprite.png

**Comment by katana-ua** [comment]
I'm back -- была работа + учила ангуляр на своих проектах... но, как вижу по изменениям, отстала безнадежно :(

**Comment by SergiiShapoval** [comment]
@katana-ua возьми таску 
Настроить бутстрап классы верстки для мобильных устройств - планшеты и смартфоны #58

посоревнуйтесь с @kaflan, кто лучше сделает, главный критерий - должно быть красиво и функционально,  таска очень сильно помогает разобраться с bootstrap, принципами responsive.

потом

Изменять количество элементов в группе слайдеров фото и видео в зависимости от ширины экрана пользователя #61

она должна быть лёгкой

**Comment by kaflan** [comment]
ок понятно сенк

**Comment by kaflan** [comment]
@katana-ua как выучила? что такое скоуп?
 =)

**Comment by kaflan** [comment]
Не было интета сегодня ребят
я не смог смержить все я делал как по видео... но у меня вот такая картинка

**Comment by kaflan** [comment]
![44](https://cloud.githubusercontent.com/assets/3959504/14820615/10dd78c6-0bd0-11e6-8481-6a9be7b16985.png)

**Comment by SergiiShapoval** [comment]
@kaflan добавь новую ветку в своей репе, запуль туда изменения,
дальше можешь делать всё, что тебе захочется - мерджить с мастером, работать только с этой веткой, которую потом добавишь пул реквестом в мастер основного проекта

**Comment by kaflan** [comment]
угу я уже понял я надеюсь я нечего вам не испортюсвоими кривыми руками

**Comment by SergiiShapoval** [comment]
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md
