### ISSUE TITLE
NLCH-0012 Добавляем виджет Reformal на все страницы сайта

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#16]
Код для вставки:

`<script type="text/javascript">
    var reformalOptions = {
        project_id: 972997,
        project_host: "nasha-lepta.reformal.ru",
        tab_orientation: "left",
        tab_indent: "50%",
        tab_bg_color: "#F05A00",
        tab_border_color: "#FFFFFF",
        tab_image_url: "http://tab.reformal.ru/0JjQtNC10Lgg0Lgg0L%252FRgNC10LTQu9C%252B0LbQtdC90LjRjw==/FFFFFF/cc80218e3bc37332f1821af78c238ad8/left/1/tab.png",
        tab_border_width: 2
    };
    
    (function() {
        var script = document.createElement('script');
        script.type = 'text/javascript'; script.async = true;
        script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'media.reformal.ru/widgets/v3/reformal.js';
        document.getElementsByTagName('head')[0].appendChild(script);
    })();
</script><noscript><a href="http://reformal.ru"><img src="http://media.reformal.ru/reformal.png" /></a><a href="http://nasha-lepta.reformal.ru">Идеи и предложения</a></noscript>`

```
<script type="text/javascript">
    var reformalOptions = {
        project_id: 972997,
        project_host: "nasha-lepta.reformal.ru",
        tab_orientation: "left",
        tab_indent: "50%",
        tab_bg_color: "#F05A00",
        tab_border_color: "#FFFFFF",
        tab_image_url: "http://tab.reformal.ru/0JjQtNC10Lgg0Lgg0L%252FRgNC10LTQu9C%252B0LbQtdC90LjRjw==/FFFFFF/cc80218e3bc37332f1821af78c238ad8/left/1/tab.png",
        tab_border_width: 2
    };
    
    (function() {
        var script = document.createElement('script');
        script.type = 'text/javascript'; script.async = true;
        script.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'media.reformal.ru/widgets/v3/reformal.js';
        document.getElementsByTagName('head')[0].appendChild(script);
    })();
</script><noscript><a href="http://reformal.ru"><img src="http://media.reformal.ru/reformal.png" /></a><a href="http://nasha-lepta.reformal.ru">Идеи и предложения</a></noscript>
```

Нужно создать отдельный js файл в public/scripts, добавить на него ссылку на всех главных страницах (проект и под-проекты)

ссылка должна размещаться в таком месте, чтобы:

1. Код минифицировался и добавлялся к остальным построенным скриптам
2. Код грузился в последнюю очередь для оптимизации загрузки

Вставленный код в файле должен быть читабельным.(используйте комбинации клавиш ctrl+alt+L и ctrl+alt+I в WebStorm)

Коммитимся в отдельную ветку reformal, ветка должна быть сделана на уровне текущего мастера главного проекта NashaLeptaChallenge/nasha_lepta, упоминаем Fixes #16

**Comment by katana-ua** [comment]
Как я понимаю - в этой строке в билд index.html:
`<script src="scripts/vendor.aa77f703.js"></script> <script src="scripts/appRootScript.2c7f8aa5.js"></script> <script src="scripts/scripts.e3ae2de0.js"></script> <script src="scripts/ckeditor/ckeditor.js"></script>`
ссылки на файлы, в которые превращаются 4 группы скриптов (из них только ckeditor остается как есть). Соответственно, если разместить ссылку на реформал.джс последней в третьей группе ссылок на скрипты - то он и минимизируется, и будет грузиться последним.

Ветка здесь: https://github.com/katana-ua/nasha_lepta/tree/reformal

Еще вопрос: фрагмент `<noscript><a href="http://reformal.ru"><img src="http://media.reformal.ru/reformal.png" /></a><a href="http://nasha-lepta.reformal.ru">Идеи и предложения</a></noscript>` ведь только для случаев, когда нет поддержки скриптов? Нужен ли он вообще, и если да - то в какую часть страницы его вставить?

**Comment by SergiiShapoval** [comment]
@katana-ua да, правильно, должен быть в третье группе

лучше коммититься с Fixes #16 - так я буду видеть каждый коммит и смогу сразу прокооментировать по каждому изменению,
в ветке ккоммиты ещё нужно найти.

часть noscript не используем: одно из мероприятий будет ссылаться на данное окошко, там понадобится модифицированный вариант

**Comment by SergiiShapoval** [comment]
добавь pull-request
