### ISSUE TITLE
NLCH-0013 Делаем автообновляемый footer.

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#17]
Сейчас в footer стоит  © Наша лепта 2015:
![footer](https://cloud.githubusercontent.com/assets/8704477/13868569/1319843e-ecd3-11e5-988b-9f63bd8e6f18.JPG)

Как разработчику сайта мне влом каждый новый год обновлять футер вручную, по этому я хочу, чтобы footer отражался в стиле © Наша лепта 2015-{текущий год}.

Для этого:
1. создайте отдельный js файл в public/scripts, 
2. добавьте на него ссылку на всех главных страницах (проект и под-проекты)
3. напишите простой алгоритм проставления значения текущего кода на JS без Ангулар (забейте в google как)

Вставленный код в файле должен быть читабельным.(используйте комбинации клавиш ctrl+alt+L и ctrl+alt+I в WebStorm)

Коммитимся в отдельную ветку footerDate, ветка должна быть сделана на уровне текущего мастера главного проекта NashaLeptaChallenge/nasha_lepta, упоминаем Fixes #17

**Comment by zizizi17** [comment]
Сергію, зробив скріпт, ось такий http://c2n.me/3vL7e9k
Підключив на сторінки http://c2n.me/3vL7ijO
Запускаю і в мене нічого не змінюється. Проте, якщо в консолі прописую ці дані, то результат виводиться, проте тільки в консолі. 
Де я помиляюсь, підкажи, будь ласка

**Comment by SergiiShapoval** [comment]
@zizizi17 Відео по JS подивився?

**Comment by zizizi17** [comment]
@SergiiShapoval яке саме відео?

**Comment by SergiiShapoval** [comment]
курс по JS який я надсилав у листах через гугл групу

**Comment by katana-ua** [comment]
Готово: http://katana-ua.github.io/nasha_lepta/#/news2016
код здесь: https://github.com/katana-ua/nasha_lepta/blob/master/public/scripts/currentYear.js
Только с веткой в течение дня разберусь - чот по-прежнему путаница выходит :(

**Comment by zizizi17** [comment]
@SergiiShapoval А можеш надіслати ще раз? Я не можу знайти на пошті.

**Comment by SergiiShapoval** [comment]
@katana-ua зачем 
`document.addEventListener("DOMContentLoaded", currentYear());`
?

http://www.w3schools.com/js/tryit.asp?filename=tryjs_dom_getelementbyid

getElementById правильный выбор - в разы быстрее работает

по веткам - 
выбери коммит на который нужно перейти,
из контекстного меню выбери Checkout revision,
![newbranch](https://cloud.githubusercontent.com/assets/8704477/13896836/5d4e6368-eda4-11e5-956b-086ba0e6d548.png)
дальше из меню веток создай новую ветку - ветка будет на уровне выбранной ревизии
дальше добавляешь свои изменения и коммитишься

@zizizi17 не могу каждому повторять все сообщения по запросу, ищи в почте, тебе точно должны были прийти

**Comment by SergiiShapoval** [comment]
@zizizi17 просмотри все сообщения через веб-интерфейс = https://groups.google.com/forum/#!forum/nasha-lepta-challenge

**Comment by zizizi17** [comment]
@SergiiShapoval так, відео дивився, але все одно не розумію, чому не можу зініціалізувати код на сторінці

**Comment by katana-ua** [comment]
Мда, оказывается, достаточно всего двух строк... О_о
Исправлено, ветка здесь: https://github.com/katana-ua/nasha_lepta/tree/footerDate

**Comment by DmytroManco** [comment]
можно для особо одаренных еще раз? Создал файл, подключил ко всем индексам, создал ветку footerDate в которой на данный момент нахожусь. Попытка закомитить предупреждает об огромном количестве варнингов.

**Comment by katana-ua** [comment]
@DmytroManco я вот этим пользовалась:
http://stackoverflow.com/questions/5561161/how-to-do-a-pull-request-in-github-with-only-the-latest-commit-in-the-master-bra
Для любителей командной строки, чот побаиваюсь вебсторма - в нем, по-моему, чайнику проще дров наломать.

**Comment by SergiiShapoval** [comment]
@katana-ua добавь pull request - закроем данную таску
