### ISSUE TITLE
NLCH-0014 Переделываем шапку сайта

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#18]
Новый header должен выглядеть вот так:
![header nl](https://cloud.githubusercontent.com/assets/8704477/13897475/d0c1e552-edba-11e5-9dfb-148fd4140cad.png)

Файл psd находится тут - https://yadi.sk/i/9eYNY3yLqNAzJ
Логотип и лента = картинки, всё остальное - текст.
Выпадающих под-меню в главном меню нету.
Окончательная цветовая схема утверждена в psd файле.
Цветовые html коды можно определить специальными программами (например pixie), либо подсмотреть в psd.
Все изменения делаем в блоке div.nl_nav
Позиционирование элементов должно быть сделано с помощью bootstrap классов

Изменения делаем в ветке header, упоминаем Fixes #18

**Comment by Dmytraw** [comment]
Не вижу псд файла. Его еще нет?

**Comment by SergiiShapoval** [comment]
@Dmytraw завтра с утра добавлю

**Comment by SergiiShapoval** [comment]
@Dmytraw обновил

**Comment by Dmytraw** [comment]
Отлично!:)

Есть одна небольшая проблема, я не знаю как с помощью grunt запустить проект для проверки вёрстки.

**Comment by Dmytraw** [comment]
комент удалил т.к разобрался сам :)

**Comment by Dmytraw** [comment]
появился другой вопрос - я никогда до єтого не верстал из псд шаблона. и никогда не перевёрстывал за другими. какие ресуры можно посмотреть дабы разобраться хотя бы с вёрсткой из псд? спасибо

**Comment by kaflan** [comment]
brackets extract посмотри там все просто

**Comment by Dmytraw** [comment]
шаблоны больше 16 мб в брэкетс экстракт не открываются

**Comment by SergiiShapoval** [comment]
я использую photoshop макет, чтобы подсмотреть какие цвета там используются, как настроены градиенты, вырезаю отдельный самый малый элемент узора, рисунки- все остальное через html css повторяю на сайте.

**Comment by SergiiShapoval** [comment]
http://bootstrapdocs.com/v3.3.4/docs/css/#buttons
