### ISSUE TITLE
NLCH-0015 Переделываем footer сайта

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#19]
Зависит от #17 

Footer будет выглядеть так:
![footer nl](https://cloud.githubusercontent.com/assets/8704477/13897578/ab9ebcc0-edbd-11e5-974f-387dfaad4492.png)
psd файл тут - https://yadi.sk/i/9eYNY3yLqNAzJ
Социальные кнопки будут на ВКонтакте, Facebook, Youtube и Google+.
Баннеры переиспользуем текущие.
Логотипы, лента картинками.
Переиспользуем динамическую дату из #17 
Изменения делаем в div.footer

изменения делаем в ветке footer, упоминаем Fixes #19

**Comment by katana-ua** [comment]
Есть - на страницы подпроектов пока не вносила, жду критики.

Еще по Wufoo напишу здесь, чтобы не множить сущности. Я не забыла, что то задание in progress - просто пару дней ушло на поиски более простых путей, которые не очень-то сработали: если в index.html стили объединить с помощью комментариев (тех, что build:css) - новый минифицированный файл вставляется на место, но в него почему-то не желает входить инфа из main.css; если же объединить vendor.css и main.css с помощью таски concat - не могу придумать, как воткнуть полученный в index.html. Но завтра еще раз попытаюсь - может, по инструкции по ссылке у меня получится, уже без самодеятельности :)

**Comment by SergiiShapoval** [comment]
Критику добавил, не вижу обновлённого вида на http://katana-ua.github.io/nasha_lepta, таску проще критиковать видя страницу, кроме того редактор сайта верстку читать не умеет

**Comment by katana-ua** [comment]
Готово. Только фон там прямо целой лентой - я только щас вот осознала свою ошибку, но узор от слоя градиента в псд что-то не отделяется :(

**Comment by SergiiShapoval** [comment]
@katana-ua 

что делает overrides?
наложи градиент с помощью css, градиент в фотошопе проставляется как свойство слоя

**Comment by katana-ua** [comment]
overrides препятствует удалению bower`ом ссылок на стили из хтмл (в данном случае font-awesome, но люди пишут, что и бутстрап 3.3.5 пропадает - т. е. баг отдельных версий некоторых пакетов).

Заменила на извлеченный из псд - прозрачный.
