### ISSUE TITLE
NLCH-0002 Getting more done in GitHub with ZenHub

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#2]
Задание NLCH-0002.
1.	Установите WebStorm https://www.jetbrains.com/webstorm/download/#section=windows-version
2.	Скачайте через WebStorm, свой личный форкнутый репозиторий nasha_lepta.
3.	Сделайте коммит с упоминанием «Fixes #1» в сообщении коммита.
4.	Удостоверьтесь, что https://github.com/NashaLeptaChallenge/nasha_lepta/issues/1 содержит Ваш коммит.
5.     Найдите на youtube видео обзор по работе с git через WebStorm, добавьте хорошое видео тут, если тут его ещё нет

Hola! @SergiiShapoval has created a [ZenHub](http://www.zenhub.io) account for the **NashaLeptaChallenge** organization. ZenHub is the leading team collaboration and project management solution built for GitHub.

----

#### How do I use ZenHub?

To get set up with ZenHub, all you have to do is **[download the browser extension](https://www.zenhub.io?utm_source=ZHOnboarding)** and log in with your GitHub account. Once you do, you’ll get access to ZenHub’s complete feature-set immediately.

#### What can ZenHub do?

ZenHub adds a series of enhancements directly inside the GitHub UI:

- Real-time, customizable task boards for GitHub issues;
- Burndown charts, estimates, and velocity tracking based on GitHub Milestones;
- Personal to-do lists and task prioritization;
- “+1” button for GitHub issues and comments;
- Drag-and-drop file sharing;
- Time-saving shortcuts like a quick repo switcher.

### [Add ZenHub to GitHub](https://www.zenhub.io?utm_source=ZHOnboarding)

_Still curious? See [more ZenHub features](https://www.zenhub.io/features?utm_source=ZHOnboarding) or read [user reviews](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd/reviews). This issue was written by your friendly ZenHub bot, posted by request from @SergiiShapoval._

![ZenHub Board](https://cloud.githubusercontent.com/assets/8771909/11153956/233ac4a8-89f1-11e5-94b1-1569d3f38b4d.png)

**Comment by tvNL** [comment]
Installed

**Comment by kaflan** [comment]
А можно атом я его уже сделал как веб сторм? ибо веб сторм платный

**Comment by SergiiShapoval** [comment]
> А можно атом я его уже сделал как веб сторм? ибо веб сторм платный

@kaflan d WebStorm есть первый бесплатный месяц, и на rutracker можно найти ключи, от Идеи должны подходить

я писал про вебсторм поскольку я с ним в основном и работаю

**Comment by Dmytraw** [comment]
Всем привет, меня зовут Дима. И я в ооочень далёкой перспективе хочу стать фулл - стаком (Пока же я нуб) :)

У меня уже есть вопрос:
Я так понял, что для комита через ВебШторм нужно внести какие-то изменения. Можно ли не делать изменений и комитнуть через Гит клиент? Спасибо.

**Comment by DmytroManco** [comment]
Привет, Дима. Нет изменений - нечего и коммитить соответственно. Посмотри как в первом ишью сделали люди. Вебшторм не обязателен, работай в любом удобном для тебя редакторе. Но я (тоже нуб) крайней рекомендую WS.

Я вот че по поводу второго задания спросить хотел. А какое то видео требуется и зачем? Лучше описать работу с гитом в Шторме, чем это сделала команда jetBrains невозможно, имхо.
https://www.jetbrains.com/webstorm/help/using-git-integration.html

**Comment by SergiiShapoval** [comment]
> А какое то видео требуется и зачем? Лучше описать работу с гитом в Шторме, чем это сделала команда jetBrains невозможно, имхо.
https://www.jetbrains.com/webstorm/help/using-git-integration.html

я там ничего не понял )), а видео показывают куда и когда нажимать :-)

как насчёт такого - https://www.youtube.com/watch?v=e67BY0y-XlA

**Comment by kaflan** [comment]
Кому удобнее атом. могу показать как сделать из него веб сторм

**Comment by kaidzen** [comment]
Всем привет!
Форкнул, закоммитил. Только вопрос. У меня есть организация на гите. Zen Hub просит авторизоваться в нее... Жду добавления в НашуЛепту, и там авторизирую его ))

**Comment by SergiiShapoval** [comment]
@kaidzen добавил

**Comment by dmytro-polupan** [comment]
Коммит через WebStorm - https://youtu.be/Hu_UFMKoKYs
