### ISSUE TITLE
NLCH-0003 Готовим проект к локальной работе

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#4]
Вот две краткие статьи по Bower, Grunt, Yeoman, которые описывают, почти то, что нам нужно на проекте:
https://www.dotnetcodegeeks.com/2015/10/node-grunt-bower-and-yeoman-a-modern-web-devs-toolkit.html
http://getinstance.info/articles/tools/how-to-use-yeoman-to-scaffold-your-next-web-app/
Видеообзор всех трех инструментов вместе тут - https://vk.com/video-27430532_171554412?list=22ceb2c1ed1154e8da
Остальное, думаю, пока не понадобится.

Хотелось бы добавить, что в Webstorm мне удобно работать с command line через вкладку Terminal, если у Вас недоступны вкладки: View - Toolbar + View - Tool buttons.
Альтернатива в Windows – Git bash, можно из просмотра папки сразу открыть command line правой клавишей мыши.
К задачам:
1.	Уcтановите на свою компьютер node.js
2.	С помощью npm установите yeoman, bower, grunt.
3.	Из терминала добавьте зависимости проекта: npm install
Что изменилось в структуре папок? Как Webstorm помогает быстро найти отличия?
Потом bower install. Обе таски займут в порядке времени. Проследите за изменениями после второй команды.
4.	Добавьте chrome plugin Live reload (поможет Grunt обновить страницу, если вы хочете видеть свои изменения на лету) https://chrome.google.com/webstore/detail/jnihajbhpnppcggbcgedagnkighmdlei
5.	Добавьте JetBrains IDE support plugin - https://chrome.google.com/webstore/detail/jetbrains-ide-support/hmhgeddbohgjknpmjagkdomcpobmllji , поможет дебажить JavaScript код на лету. 
6.	Отметьте плюсом данное задание на github, используя плагин ZenHub, когда закончите, чтобы я понимал Ваш прогресс.

**Comment by Dmytraw** [comment]
всем привет. я тут пытаюсь поставить grunt, а мне гит баш выдаёт море ошибок. может мне кто-то подсказать в чём дело? 
![image](https://cloud.githubusercontent.com/assets/12999073/13524192/7b501986-e202-11e5-9ff2-37b6128387cd.png)

**Comment by kaflan** [comment]
![18](https://cloud.githubusercontent.com/assets/3959504/13524258/d82f84fc-e202-11e5-8992-408e5c9d921c.png)
это флаг?

**Comment by kaflan** [comment]
@Dmytraw  во первых открывай его через права админа, 
во вторых ставь флаг -g
и должен быть профит

**Comment by Dmytraw** [comment]
@kaflan о, вот фишка с -g помогла, спасибо. а то там по ссылке (https://www.dotnetcodegeeks.com/2015/10/node-grunt-bower-and-yeoman-a-modern-web-devs-toolkit.html) вроде не просили -g прописывать. спасибо :)

**Comment by kaflan** [comment]
@Dmytraw  посмотри скрин каст илльи канотра по ноде может больше поймешь как оно

**Comment by kaflan** [comment]
npm install чето не хочет устанавливать

**Comment by kaflan** [comment]
npm WARN EPACKAGEJSON nashalepta@0.0.0 No license field.

**Comment by kaflan** [comment]
@Dmytraw  у тебя поставилось все локально? у меня кроме бовера нет. грант у меня есть. но чего он не ставиться локально не пойму

**Comment by kaflan** [comment]
@SergiiShapoval  хелп. руки клешни. не могу понять почему нод модулес не ставиться. чо делать?

**Comment by kaflan** [comment]
@SergiiShapoval  я поставил все в ручную через флаг -D

**Comment by kaflan** [comment]
@SergiiShapoval  может изза того что у меня нода 5 я? он не хавал  хз yoman angular ok работает

**Comment by kaflan** [comment]
о боже лендинг просто ад =)

**Comment by kaflan** [comment]
если у кого то не поставился npm install 
npm install -D grunt grunt-autoprefixer grunt-build-control grunt-concurrent grunt-contrib-clean grunt-contrib-concat grunt-
contrib-connect  grunt-contrib-copy  grunt-contrib-cssmin grunt-contrib-htmlmin grunt-contrib-imagemin  grunt-contrib-jshint grunt-contrib-uglify grun
t-contrib-watch grunt-filerev grunt-google-cdn  grunt-karma grunt-newer grunt-ng-annotate  grunt-svgmin grunt-usemin grunt-wiredep  jshint-stylish kar
ma-jasmine karma-phantomjs-launcher load-grunt-tasks time-grunt

**Comment by katana-ua** [comment]
Готово, и даже разобралась с бОльшей частью выдаваемых сначала ошибок. Теперь почти все ОК, кроме этого:
`C:\Users\thetis\repos\nasha_lepta>npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN grunt-karma@0.11.2 requires a peer of karma@^0.12 || >= 0.13.0-rc.0 but none was installed.
npm WARN karma-jasmine@0.3.7 requires a peer of jasmine-core@* but none was installed.
npm WARN karma-phantomjs-launcher@0.2.3 requires a peer of karma@>=0.9 but nonewas installed.
npm WARN karma-phantomjs-launcher@0.2.3 requires a peer of phantomjs@>=1.9 but none was installed.
npm WARN nashalepta@0.0.0 No license field.`

Я так понимаю, эти компоненты относятся к тестированию. Они необходимы, нужно их доставить?

И второй вопрос - в index.html ссылки на таблицы стилей, которые находятся в папке bower_components. Что делать - менять ссылки на "../bower_components/..."? Перемещать bower_components в public? О_о

**Comment by zizizi17** [comment]
Гайз, а як зурбом відмітити, що виконав це завдання?

**Comment by zizizi17** [comment]
http://c2n.me/3vaCqMV
Гайз, в мене така штука.
Як пофіксити? 
Path прописав правильний.

**Comment by katana-ua** [comment]
У меня npm ругался на отсутствие пакетов:
`C:\Users\thetis\repos\nasha_lepta>npm install
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN grunt-karma@0.11.2 requires a peer of karma@^0.12 || >= 0.13.0-rc.0 but none was installed.
npm WARN karma-jasmine@0.3.7 requires a peer of jasmine-core@* but none was installed.
npm WARN karma-phantomjs-launcher@0.2.3 requires a peer of karma@>=0.9 but nonewas installed.
npm WARN karma-phantomjs-launcher@0.2.3 requires a peer of phantomjs@>=1.9 but none was installed.
npm WARN nashalepta@0.0.0 No license field.`
(npm WARN здесь - это начало каждой строки результата).

Я просто дописала в package.json названия недостающих пакетов с соответствующим номером версии, и все установилось (осталось это сообщение: `npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm WARN nashalepta@0.0.0 No license field.`, но раз optional dependency - на работу, можно надеяться, не повлияет?)

**Comment by SergiiShapoval** [comment]
@kaflan, @katana-ua в четверг вечером делал установку с чистого листа у себя,
нода у меня была последняя актуальная на август 2015,
много ругался WARN, что нужно обновить зависимости, но всё установил без ошибок,

bower также само

потом grunt serve нормально работал - это главный критерий правильного прохождения шага


 @NashaLeptaChallenge/team  кто хочет, может подготовить pull-request с обновлёнными зависимостями в package.json + bower.json, на которые не ругается последняя версия ноды, я его добавлю в основной проект

**Comment by SergiiShapoval** [comment]
@kaflan в следующий раз осветить все свои проблемы, до конца разобравшись в чём дело, в одном сообщении было бы лучше, такой подход выглядел бы профессионально, а то куча уведомлений пошла на всех участников обсуждения

**Comment by garyker** [comment]
![npm.png](https://files.zenhub.io/56dad29f93fd4909417cc122)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)
что то пошло не так

**Comment by garyker** [comment]
![npm](https://cloud.githubusercontent.com/assets/11088028/13547528/b830b0bc-e2df-11e5-9df5-29d5d405b3de.png)
Что то пошло не так. Ubuntu 15.10

**Comment by kaflan** [comment]
@SergiiShapoval ок

**Comment by garyker** [comment]
http://localhost:9000/#/news2016 - проект запустился.

**Comment by kaidzen** [comment]
Народ, а нода какой версии?
yeoman не хочет ставиться на 5,7,1 ноду...
З.Ы.: а в скайпе может группу создадим? Для быстрых вопросов-ответов? ;-)

**Comment by Shketkol** [comment]
Давайте. Так будет адекватнее, или можно использовать слак. А где ставить + в плагине ZenHub

**Comment by garyker** [comment]
Поддерживаю, garryker - мой логин в скайпе, добавьте если создали группу

**Comment by Shketkol** [comment]
Группа https://join.skype.com/k0ku3YcPbT1k

**Comment by tvNL** [comment]
Установил node, yeoman, bower, grunt

Сделал npm install - в папке проекта появилась папка node_modules в которой более 16 000 файлов (это нормально или что-то лишнее притянулось?).

К сожалению не понял "Как Webstorm помогает быстро найти отличия?" Подскажите пожалуйста. Это не предупреждения справа от исходного текста о том что он не может найти какую-либо директорию?

После bower install появились папки bower_components и .idea

Установил "Live reload" и "JetBrains IDE support plugin"

Попробовал grunt serve - запустился проект по адресу http://localhost:9000/#/news2016

**Comment by SergiiShapoval** [comment]
@tvNL 

> появилась папка node_modules в которой более 16 000 файлов (это нормально или что-то лишнее притянулось?).
нормально

> К сожалению не понял "Как Webstorm помогает быстро найти отличия?" Подскажите пожалуйста. 
папки в файл менеджере проекта созданные во время билда и выкачанные из git отличаются по цвету

> После bower install появились папки bower_components и .idea

.idea отвечает за конфигурацию Webstorm проекта

> Попробовал grunt serve - запустился проект по адресу http://localhost:9000/#/news2016
то, что надо

**Comment by ArtemMaznov** [comment]
@SergiiShapoval не могу полностью разобраться с установкой npm install.
из новых папок только .idea

**Comment by SergiiShapoval** [comment]
@ArtemMaznov как думаешь, чтобы ответили на stackoverflow на такой вопрос?
На что должен опираться отвечающий?

Напиши хотя бы что было сделано и какой был ответ от запуска команды, лучше бы с уместными скриншотами

**Comment by dmytro-polupan** [comment]
Уставнока билдеров - https://youtu.be/Mwee70dr0V4

Установка зависимостей проекта - https://youtu.be/g-rmh4nzLzU

**Comment by ArtemMaznov** [comment]
@dmytro-polupan спасибо за ссылки на видео. я допустил банальную ошибку. при установке зависимостей проекта не указал папку проекта.
