### ISSUE TITLE
NLCH-0004 Запускаем-билдим проект локально. Готовим свою личную github-page

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#5]
1.	Откройте вкладку с кабаном – grunt в Webstorm.
2.	Запустите проект локально – serve, стопните, когда задача больше не нужна будет
3.	Соберите проект – build
Как изменилась структура папок?
Какие особенности новых файлов? 
Какая разница между ссылками на внешний файлы на главной странице базового проекта и собранного, а в подстраницах проекта?
4.	А что если запустить туже задачу из консоли командой – grunt -v serve, в чём разницу?
5.	Запушьте проект на github-pages, 
6.	Сделайте так, чтобы он всё таки запушил на вашу собственную страницу. 
Используйте уроки mastering github. 
Не нашли - поройтесь в Gruntfile.js. 
Ещё не нашли – просмотрите историю изменений только файла  Gruntfile.js в git: нажмите правой клавишей на поле файла-Git-Show History. 

Обратите внимание на Local History – Show History, удобное меню, если наделали изменений не комитясь, а хочете вернутся к одному из предыдущих промежуточных состояний. Настройте его под себя в выпадающих меню сверху окошка истории (картинка видна только тем, кто установил ZenHub
![mywebstormscreenshot](https://cloud.githubusercontent.com/assets/8704477/13518183/f513328c-e1d3-11e5-9a49-72b640862a4c.JPG)
)
7.	Что не так в Вашей github-page? Почему так происходит? Как вручную это исправить в собранном грантом проекте? Найдите обсуждение этого бага гранта в гугл.
8.	Плюсуем по мере прогресса.

**Comment by kaflan** [comment]
https://gist.github.com/kaflan/dee83ef0361f54027535

**Comment by kaflan** [comment]
grunt serve запустить сервер локально
grunt build  билд проэкта
grunt -v serve не буду спойлерить

**Comment by kaflan** [comment]
Warning: Loading "grunt-karma.js" tasks...ERROR
>> Error: Cannot find module 'karma'
 я могу убрать ее но почему у меня так?

**Comment by kaflan** [comment]
подсказка чтобы билд отработал нормально найдите в нод модулях 
"imagemin": "^4.0.0",

**Comment by kaflan** [comment]
вот такое значиене должно быть это решает вопрос

**Comment by kaflan** [comment]
https://github.com/gruntjs/grunt-contrib-imagemin/issues/330 решение тут

**Comment by MaxBabenko** [comment]
подскажите, "grunt -v serve" что за флаг   -v   ?

**Comment by SergiiShapoval** [comment]
@kaflan попробуй обновить нод, сделай чистую инсталяцию

**Comment by Shketkol** [comment]
А можно по детальнее как все сделать, а то не очень понятно

**Comment by kaidzen** [comment]
https://github.com/kaidzen/nasha_lepta/commit/5a563d93395dc5e933e61c6ebbe2beeaa7fdae9c

**Comment by kaidzen** [comment]
Кстати, а какой лучше оставить в шторме:

**Comment by kaidzen** [comment]
![image](https://cloud.githubusercontent.com/assets/11272209/13549437/d4009ebe-e30d-11e5-98fa-6e70aa52cf23.png)

**Comment by SergiiShapoval** [comment]
@kaidzen Editorconfig отвечает за форматирование текста при коммите = твоя IDE будет настроена под тебя, но во время коммита форматирование автоматически изменится так, как прописано в EditorConfig,

текущие настройки сконфигурированы yeoman, я их не менял.

@Shketkol где именно нужны детали?

@kaidzen вижу + на задании, не вижу рабочего сайта на http://kaidzen.github.io/nasha_lepta

задачи, начиная с 5, специально не расписывал в деталях, чтобы Вы сами порылись в гранте, его настройках и истории коммитов.

Если никто не решит - добавлю деталей, 

если не получается, сделайте пока следующие. Возможно, они подскажут решение

**Comment by Shketkol** [comment]
http://shketkol.github.io/nasha_lepta/#/news2015

**Comment by katana-ua** [comment]
Разница между serve и -v serve: v - это verbose, т.е. подробный отчет про весь процесс запуска, перечисление всех файлов, за изменениями в которых грант следит...

После build - появилось еще несколько папок, отмеченных в .gitignore. В базовом проекте ссылки на bower_components, в собранном - файлы минимизированные, ссылки на CDN.

Дальше сегодня буду разбираться, т.к. все время ушло на codeschool (зато теперь знаю, что такое ангуляр и с чем его едят)).

**Comment by kaflan** [comment]
@Shketkol как ты так сделал?

**Comment by kaflan** [comment]
я просто понимаю как с обычными страничками в гит пейджес... тут как то я потерялся... может кто подсказать как комитнуть правильно

**Comment by katana-ua** [comment]
@kaflan Подсказка: ищи в gruntfile.js описание модуля grunt-build-control - из него должно стать все ясно. Плюс см. историю изменений gruntfile.js с самого начала. Остальное - в видео Mastering Github.

**Comment by kaflan** [comment]
@katana-ua ой я знаю... что билд это уже конечный результ я просто как его вставить

**Comment by kaflan** [comment]
@katana-ua  но спасиб за подсказку

**Comment by katana-ua** [comment]
@kaflan Тот модуль его и вставляет в нужную ветку.

**Comment by kaflan** [comment]
фига себе окей посмотрю как он работает спасибо

**Comment by kaflan** [comment]
@katana-ua  там по видосикам я тогда разберусь в гитхаб пейджес? и этой чтуке... окей историю изменений тоже посмотрю в атоме... только вопрос как...

**Comment by garyker** [comment]
запнулся на 5-м пункте "Запушьте проект на github-pages"

**Comment by DmytroManco** [comment]
У меня тоже проблемы с пушем. Выдает: "gh-pages (non-fast-forward)".

"https://help.github.com/articles/dealing-with-non-fast-forward-errors/" эти решения не помогают.

**Comment by kaflan** [comment]
grunt buildcontrol

**Comment by kaflan** [comment]
почему билд идет не правильно?

**Comment by DmytroManco** [comment]
non-fast-forward errors при пуше. 
https://help.github.com/articles/dealing-with-non-fast-forward-errors/ - решения не помогают.

**Comment by katana-ua** [comment]
@kaflan Билд идет правильно - так, как ему приказано в грантфайл.джс
Задай такой вопрос: почему индекс.хтмл не видит папки стилей и скриптов? Ответ можно найти как в индекс.хтмл, так и в грантфайл.джс

**Comment by kaflan** [comment]
@katana-ua  КЕП... ктото настроил грант не правильно ай ай =)

**Comment by kaflan** [comment]
@katana-ua просто я без понятия как это настроить

**Comment by kaflan** [comment]
сделал... помог ментор

**Comment by SergiiShapoval** [comment]
@Shketkol или @MaxBabenko сможете тут описать, как Вы пришли к решению (текст + скриншоты WebStorm и github ) = создать manual для других участников?
я подкорректирую, если будет надо

в описании должны быть ответы на вопросы других участников:

> запнулся на 5-м пункте "Запушьте проект на github-pages"

> non-fast-forward errors при пуше. 
https://help.github.com/articles/dealing-with-non-fast-forward-errors/ - решения не помогают.

> @garyker grunt buildcontrol вот но страница выглядет не так как нужно
почему хз
почему билд идет не правильно? как это исправить?

**Comment by Shketkol** [comment]
Сегодня вечером постараюсь описать процесс. Работы просто много, если кому-то не ответил, сори

**Comment by Shketkol** [comment]
процесс брал  http://blog.teamtreehouse.com/using-github-pages-to-host-your-website

**Comment by Shketkol** [comment]
также смотрите https://pages.github.com/
вкладка project site -> Start from scratch

**Comment by SergiiShapoval** [comment]
@NashaLeptaChallenge/team 

я обновил package.json

все у кого не проходил grunt build без ошибок - выкачайте репозиторий заново, 
сделайте npm cache clean,
повторите npm install, bower install,
запустите grunt build,

если опять будут ошибки - пишите, билд и установка должны проходить чисто без дополнительных ручных изменений

сегодня вечером или завтра с утра вышлю видео урок по большей части шагов из заданий 1-6.

**Comment by dmytro-polupan** [comment]
Пушим проект на гитхаб из грант таски - https://youtu.be/SY4uoSh_oP8

**Comment by ArtemMaznov** [comment]
@SergiiShapoval  у меня при открытии gruntfiles.js вкладкою grunt выдает "! Failed to list tasks details. " и не подтягиваются таски.

**Comment by zizizi17** [comment]
А підкажіть, будь ласка, якщо мій гітхаб пейдж зайнятий, я ж новий не можу створити. Що мені з цим робити?

**Comment by kaflan** [comment]
@zizizi17 где он занят почитайте внимательней про гитхаб пейджес все ок должно быть

**Comment by SergiiShapoval** [comment]
@ArtemMaznov переустанови грант глобально, переоткрой проект,

@zizizi17 як це він зайнятий, якщо порожній - http://zizizi17.github.io/nasha_lepta

**Comment by kaidzen** [comment]
@SergiiShapoval  Выпал из процесса немного. Родственник приболел, скорые больницы, брр...
Все исправил: http://kaidzen.github.io/nasha_lepta/#/news2016

**Comment by SergiiShapoval** [comment]
@kaidzen ok, включайся сегодня большой update высылал

**Comment by zizizi17** [comment]
гайз, поміняв шляхи до css i js файлів, але все одно не відображається

**Comment by SergiiShapoval** [comment]
@zizizi17 порівняй http://dmytro-polupan.github.io/nasha_lepta/nikolsky_evenings/  та http://zizizi17.github.io/nasha_lepta/nikolsky_evenings/, 
http://sergiishapoval.github.io/nasha_lepta/ та http://zizizi17.github.io/nasha_lepta/

у вкладках Networs, Console у Dev Chrome Tools

в тебе не викачані всі залежності bower скоріше всього

**Comment by tvNL** [comment]
Прошу прощения за то, что сильно выпал из процесса. Надеюсь смогу догнать.
Это задание выполнил: 
[http://tvnl.github.io/nasha_lepta](http://tvnl.github.io/nasha_lepta)

**Comment by garyker** [comment]
@tvNL Аналогично отстал от рпоекта и пытаюсь догнать. Застрял на моменте выглузки проекта на gh-pages. Вот что получается http://garyker.github.io/nasha_lepta/
Подскажи, как добился коректного отображения страницы?

**Comment by kaflan** [comment]
@tvNL там есть в гранте история файлов посомтри. увидешь что вставлять

**Comment by tvNL** [comment]
@garyker  " Подскажи, как добился коректного отображения страницы?"
просто сделал всё как в видеоуроке [https://www.youtube.com/watch?v=SY4uoSh_oP8](https://www.youtube.com/watch?v=SY4uoSh_oP8)

**Comment by garyker** [comment]
Все что описывается в задании я выполнил, разобралс что к чему, но отсается непонятным момент с уделенными репозиториями. Для того, что мы запушить проект на https://pages.github.com/, какую из веток проекта мне нужно пушить?

**Comment by SergiiShapoval** [comment]
@garyker посмотри ещё раз внимательно все видео от начала до конца

**Comment by garyker** [comment]
http://garyker.github.io/nasha_lepta/#/news2016 вот что получилось

**Comment by garyker** [comment]
Может я что то не так делаю, не выходит...

Находясь на ветке masterредактирую insex.html как показано в видео. Так же редактирую конф. гранта, подставляю свой репозиторий и токен, пушу проект на gh-pahes, получаю  http://garyker.github.io/nasha_lepta/#/news2016, что я не так делаю?

**Comment by SergiiShapoval** [comment]
@garyker было бы неплохо обновить проект до последнего - https://github.com/garyker/nasha_lepta/pull/1, потом выкачать ещё раз все зависимости, 

потом проверить grunt serve, что всё нормально работает локально

потом запушить на свои страницы github 
если не получится - повторить на чисто, в новой папке, предварительно установив последнюю ноду

**Comment by garyker** [comment]
@SergiiShapoval проделал все, что описано выше, не отрабатывает таска buildcontrol:pages с варнингом Warning: ENOENT: no such file or directory, open './logs/grunt.log' Use --force to continue.

**Comment by katana-ua** [comment]
@garyker удали logfile-grunt (`npm uninstall logfile-grunt --save-dev`) и строки `require('logfile-grunt')(grunt);` из Gruntfile.js (там 1 или 2 строки с комментарием где-то в начале).

**Comment by garyker** [comment]
@katana-ua спасибо

**Comment by garyker** [comment]
@SergiiShapoval @katana-ua спасибо за помощь, все получилось http://garyker.github.io/nasha_lepta/#/news2016
