### ISSUE TITLE
Настроить бутстрап классы верстки для мобильных устройств - планшеты и смартфоны

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#58]
- [ Шапка sm + xsm ] 
  логотип и ссылку на никольский сайт убрать;
  добавить отдельную кнопку выпадающего меню.
- [ Слайдер ]
  sm: убрать надписи справа;
  xsm: описания слайда по всей ширине;
- [ Мероприятия ]
  sm: по 2
  xsm; по 1
- [ Новости ]
  sm - фото на половину
  xsm - фото на всю ширину
- [ Footer ]
  sm - Соцсети + Партнёры по половине экрана, затем лого и лента c датой
  xsm - соцсети блок по всей, затем партнёры по всей, затем лого, лента с датой

**Comment by kaflan** [comment]
окей это я могу но как мне сделать пулл реквест сделай мне видео
плизз я не могу понять как тут пулл реквест делать

**Comment by SergiiShapoval** [comment]
https://github.com/NashaLeptaChallenge/nasha_lepta/wiki/%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC-%D0%BB%D0%B8%D1%87%D0%BD%D1%8B%D0%B9-%D1%80%D0%B5%D0%BF%D0%BE%D0%B7%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%B9-%D0%BD%D0%B0%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B0%D0%BC%D0%B8-%D0%B4%D1%80%D1%83%D0%B3%D0%BE%D0%B3%D0%BE-%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%B0

**Comment by kaflan** [comment]
спасибо

**Comment by SergiiShapoval** [comment]
@kaflan сколько времени тебе нужно чтобы сделать?

**Comment by kaflan** [comment]
я займусь этим во вторник я думаю за день зделаю спасибо сорян я просто занят много чем и сразу

**Comment by kaflan** [comment]
так я обновил репо но у меня еще старая версия
почему?

**Comment by kaflan** [comment]
интернет перестал лагать соеденил все куски сечас подправлю данные

**Comment by kaflan** [comment]
епт у меня сегодня целый день скакал как москаль на майдане инет ребят будет завтра к вечеру все

**Comment by SergiiShapoval** [comment]
@kaflan , @katana-ua вместо "Фото галлереи" и "Видео галлереи" будут "СМИ о проекте" и "Акции"

**Comment by SergiiShapoval** [comment]
добавил изменения в мастер

**Comment by kaflan** [comment]
так комитнул делать пулл реквет?

**Comment by SergiiShapoval** [comment]
разверни вначале на своей github-pages

**Comment by kaflan** [comment]
http://kaflan.github.io/nasha_lepta/#/

**Comment by kaflan** [comment]
http://kaflan.github.io/nasha_lepta/

**Comment by kaflan** [comment]
на сервере все норм опять чото настроить там надо?

**Comment by SergiiShapoval** [comment]
лентяй, просмотри опять все видео

**Comment by kaflan** [comment]
http://kaflan.github.io/nasha_lepta/#/
во сорян да помогло видео я  просто давно нечего не делал вот

**Comment by SergiiShapoval** [comment]
что то явно пошло не так 
![screen](https://s3.amazonaws.com/diigo/8454750_312487936_22818706?AWSAccessKeyId=0R7FMW7AXRVCYMAPTPR2&Expires=1461770311&Signature=ytswLcHFMkhL6nYCnCHFYCAEKl8%3D)

**Comment by kaflan** [comment]
не вижу скрина

**Comment by SergiiShapoval** [comment]
@kaflan 
![logo_issue](https://cloud.githubusercontent.com/assets/8704477/15146868/3b541000-16c6-11e6-8152-3eefbfaebc81.JPG)

**Comment by SergiiShapoval** [comment]
@kaflan можешь глянуть коммиты, всё получилось довольно просто
