### ISSUE TITLE
NLCH-0005 Дебажим JavaScript код.

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#6]
Программист, имхо, в первую очередь исследователь. Не всегда, программа работает, так как должна рабо тать или так, как описывают, что она должна рабо тать. По этому дебаг имхо, очень важный навык.
Попробуйте продебажить  код, например nlArticle.js:
1.	Запустите грантом проект локально - serve
2.	Настройте в WebStorm конфигурацию дебага:
 ![debugconfig](https://cloud.githubusercontent.com/assets/8704477/13518483/0453e4f0-e1d7-11e5-97f0-cafb3aad63c1.JPG)
Или из меню Run
![debugconfigwindow](https://cloud.githubusercontent.com/assets/8704477/13518488/0c3f456a-e1d7-11e5-85ce-e73a25311717.JPG)
a.	URL такой, на котором хранится наш локальный сервер
b.	Выберите папку public
c.	Сохраните конфигурацию
3.	Поставьте точку останова в nlArticle.js
4.	Запустите конфигурацию в debug mode
5.	Проверьте совпадают ли порты в JetBrains IDE plugin и в запущеной конфигурации debug mode. Настройте плагин, если нет.
6.	Сайт должен перестать загружаться, когда дойдёт до точки останова.
7.	Просмотрите переменные, их "внутренности".
8.	Поставьте следующую точку останова. Проскочите от текущей сразу к следующей.
9.	Походите пошагово.
10.	А зачем там калькулятор во вкладке дебага?..
11.	Плюсуем по мере выполнения

**Comment by Dmytraw** [comment]
я сделал єтот пункт

**Comment by kaflan** [comment]
@Dmytraw  я обычно дебажу в браузере

**Comment by SergiiShapoval** [comment]
Обзор дебага в WebStorm - https://youtu.be/GzFyl2Ccjrw

**Comment by kaflan** [comment]
@SergiiShapoval будь добр может есть чтото такое в атоме... или можно юзать пхп сторм? есть просто ключик надолго у друга

**Comment by SergiiShapoval** [comment]
нет, только WebStorm)), он  для OpenSource бесплатен - https://www.jetbrains.com/buy/opensource/

3 месяца у нас уже есть) https://www.jetbrains.com/buy/opensource/

кому нужна лицензия прямо от JetBrains - подавайте заявку, у меня выигранная на конференции

**Comment by kaidzen** [comment]
Вопрос по шторму: не появляются вкладки Grunt и NPM
Я из командной строки делаю, но как Шторм заставить? Что-то не получается ((

**Comment by SergiiShapoval** [comment]
возможно, старая версия если toolbars включены

**Comment by zizizi17** [comment]
Коли залишаю порт в плагіні, який і був(63342), то ось такий от результат
http://c2n.me/3vterpK
А коли змінюю на 9000, то воно взагалі не запускає сторінку.
Можна якось пофіксити?

**Comment by SergiiShapoval** [comment]
під час запуску дебагу вебсторм повідомляє на якому порту, очікує роботу плагіну, під цей порт і треба підлаштувати плагін, решта як у відео і завданні

**Comment by zizizi17** [comment]
так, воно пише, що очікує роботу на порті 63342, що є дефолтним в розширенні
але при запуску видає ось таке http://c2n.me/3vu1jBI

**Comment by SergiiShapoval** [comment]
а grunt serve сделал ?))

**Comment by zizizi17** [comment]
зробив, запрацювало, але в консолі пише "angiular is not defined" 
це мені його збілдити тоді треба чи що?

**Comment by zizizi17** [comment]
http://c2n.me/3vvOu8n
а чого воно мені ось таке видає при дебазі?
зробив grunt build, потім grunt serve і запускаю через дебаг і мені ось таке видає

**Comment by SergiiShapoval** [comment]
@zizizi17 https://github.com/NashaLeptaChallenge/nasha_lepta/issues/9#issuecomment-195879727

**Comment by zizizi17** [comment]
@SergiiShapoval в мене всі залежності такі самі, все втановлено. 
але воно все одно не працює
можливо  помилка десь в коді локально, коли воно білдить чи сервить?

**Comment by katana-ua** [comment]
@SergiiShapoval Для получения opensource-лицензии на вебсторм требуется ссылка на файл лицензии проекта, которого нету :(

**Comment by SergiiShapoval** [comment]
@zizizi17 мабуть десь помилка в коді локально

@katana-ua если это единственное, что отделяет нас от опенсорс лицензий WebStorm, давайте добавим MIT лицензию в package.json (https://github.com/gre/bezier-easing/blob/master/package.json) и в виде файла - 
https://opensource.org/licenses/MIT,
https://github.com/revdancatt/MIT/blob/master/LICENSE


или Apache 2.0 - http://www.apache.org/licenses/LICENSE-2.0.html, https://github.com/milanvavra/apache/blob/master/LICENSE

**Comment by katana-ua** [comment]
@SergiiShapoval Сделала, запушила к себе. НО: у меня там, кроме этого добавления лицензии, другие изменения (токены, firebase и т.д.), которые  нет смысла тащить в основную версию. Так что - не нужно подавать пул риквест? Или при его приеме все равно выбирается, какие из изменений принять?

**Comment by SergiiShapoval** [comment]
@katana-ua если я правильно помню, то во время pull-request можно выбирать, какие файлы-коммиты будут добавляться

**Comment by SergiiShapoval** [comment]
@katana-ua 

1. создай ветку license на текущем уровне мастера NashaLeptaChallenge/nasha_lepta в своем репозитории, если там уже есть твои коммиты, создай её до первого твоего коммита
2. забери с помощью cherry pick опции коммиты из твоего мастера в созданную ветку
3. сделай pull request с созданой ветки license в ветку мастера NashaLeptaChallenge/nasha_lepta

**Comment by katana-ua** [comment]
@SergiiShapoval В командной строке показывает как надо - добавление только последнего коммита, но в гитхабе в этой ветке почему-то все вместе. Если не получилось - отклони, пожалуйста, буду разбираться.

**Comment by kaflan** [comment]
@SergiiShapoval  не могу + gjcnfdbnm

**Comment by SergiiShapoval** [comment]
@katana-ua отклонил,

@kaflan https://github.com/NashaLeptaChallenge/nasha_lepta/issues/9#issuecomment-197684768

**Comment by tvNL** [comment]
Выполнено
