### ISSUE TITLE
NLCH-0006 Изучаем историю проекта

### ISSUE THREAD

**Issue by SergiiShapoval** [NashaLeptaChallenge/nasha_lepta#7]
Да, иногда приходится побыть и в роли историка. Особенно на больших проектах. Особенно, когда непонятно у кого спросить, или почему сделано так, или что произошло за мой отпуск )).
1.	Откройте вкладку Changes в WebStorm.
2.	Перейдите на tab log
3.	Поройтесь в отдельных изменениях
4.	Верните проект к одной из предыдущих версий и запустите его локально.

Да, таким образом можно проследить создание проекта с нуля до текущего состояния, причём в ускоренной перемотке. Так можно увидеть развитие отдельной фичи.
Плюсуем, когда закончите.

**Comment by kaflan** [comment]
угу. окей. кароч только веб сторм.. и нечего кроме него... как то ну сковывает чтоли

**Comment by SergiiShapoval** [comment]
@kaflan используй, что хочешь, я предложил работать в IDE, которая считается передовой при разработке приложений на JS и которая мне лично нравится своим удобством.
Использование одной IDE всей командой, позволяет избежать лишней неразберихи

**Comment by SergiiShapoval** [comment]
Работа с ветками гитхаба в ВебШторме - https://youtu.be/F14RTiO3bc0

**Comment by kaidzen** [comment]
Вебсторм - гуд. Я в Идее работал, все удобно и одинаково ;-)

**Comment by tvNL** [comment]
@SergiiShapoval не могу никак найти "вкладку Changes в WebStorm"
Подскажите пожалуйста.

**Comment by garyker** [comment]
@tvNL аналогично не нашел, но историю изменений файла можно по правой кливише - git - show history

**Comment by tvNL** [comment]
@garyker спасибо, это я то же нашел

**Comment by SergiiShapoval** [comment]
@tvNL , @garyker смотрите в видео по работе с ветками https://youtu.be/F14RTiO3bc0 там всё показано

**Comment by tvNL** [comment]
Задание выполнено.

@SergiiShapoval правильно ли я понял, что под "вкладкой Changes в WebStorm" вы имели ввиду "Version Control" на "Tool Buttons"?

**Comment by SergiiShapoval** [comment]
да
